// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebFile.Share.Data;

#nullable disable

namespace WebFile.BlazorServer.Migrations
{
    [DbContext(typeof(WebFileContext))]
    [Migration("20231126100654_AddFileModelTable")]
    partial class AddFileModelTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("WebFile.BlazorServer.Data.FileModel", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("UserModelUserName")
                        .HasColumnType("varchar(256)");

                    b.HasKey("Path");

                    b.HasIndex("UserModelUserName");

                    b.ToTable("FileModel");
                });

            modelBuilder.Entity("WebFile.BlazorServer.Data.UserModel", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebFile.BlazorServer.Data.FileModel", b =>
                {
                    b.HasOne("WebFile.BlazorServer.Data.UserModel", null)
                        .WithMany("Files")
                        .HasForeignKey("UserModelUserName");
                });

            modelBuilder.Entity("WebFile.BlazorServer.Data.UserModel", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
